### ISSUE TITLE
Crash Bug CDN investigation

### ISSUE THREAD

**Issue by jonasstrehle** [unyt-org/datex-core-js-legacy#23]
Linked to https://github.com/unyt-org/cdn/issues/6

I can only reproduce this behaviour on the live CDN / staging CDN, not in the local setup. DATEX and UIX used by the CDN are in the latest version.

It seems that what causes the crash is that `SCOPE.internal_vars` is an object instead of a map: https://github.com/unyt-org/datex-core-js-legacy/blob/9b042f9ea213b18ad70785784456dee7edbd647f/compiler/compiler.ts#L1336

````ts
internal_vars: <js:Object> {},
internal_primitive_vars: <Map> [],
serialized_values: <js:Object> {},
````

When catching the missing .has method on the internal_vars property there seems to occur some other bug: 
```ts
error: Uncaught (in promise) TypeError: SCOPE.jmp_indices is not iterable
for (const [i] of SCOPE.jmp_indices)
....
```

How can this occur? Is it some old endpoint sending invalid data or something else?
What is your guess @benStre?

**Comment by benStre** [comment]
> internal_vars: <js:Object> {},

The DATEX types are not really conclusive here, but that looks correct. `internal_vars` is a WeakMap, not a Map, and gets mapped to `js:Object` because it has no corresponding DATEX type implementation.

Looks like the error has some other cause

**Comment by jonasstrehle** [comment]
At least that somehow caused „SCOPE.internal_vars.has“ to fail. Either internal_vars is undefined or is a plain object instead of a WeakMap.
I just added the ? for debugging purposes.

**Comment by benStre** [comment]
Was the "Scope is missing internal_vars" error definitely not logged?

**Comment by benStre** [comment]
> At least that somehow caused „SCOPE.internal_vars.has“ to fail. Either internal_vars is undefined or is a plain object instead of a WeakMap. I just added the ? for debugging purposes.

If it was a plain object, it would be mapped to `std:Object` instead of `js:Object`

**Comment by benStre** [comment]
How exactly is this related to https://github.com/unyt-org/cdn/issues/6?

**Comment by jonasstrehle** [comment]
Scope is missing internal_vars is logged:
![Screenshot 2024-01-12 at 17 10 40](https://github.com/unyt-org/datex-core-js-legacy/assets/27917349/041bfd2c-014f-4b60-845d-7ec73eed5415)
